steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/${PROJECT_ID}/hostspace-demo/hostspace-demo:${COMMIT_SHA}', '.']

# Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/${PROJECT_ID}/hostspace-demo/hostspace-demo:${COMMIT_SHA}']

# Create an additional tag for 'latest'
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'europe-west1-docker.pkg.dev/${PROJECT_ID}/hostspace-demo/hostspace-demo:${COMMIT_SHA}', 'europe-west1-docker.pkg.dev/${PROJECT_ID}/hostspace-demo/hostspace-demo:latest']

# Push the 'latest' tag
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/${PROJECT_ID}/hostspace-demo/hostspace-demo:latest']

images:
- 'europe-west1-docker.pkg.dev/${PROJECT_ID}/hostspace-demo/hostspace-demo:${COMMIT_SHA}'
- 'europe-west1-docker.pkg.dev/${PROJECT_ID}/hostspace-demo/hostspace-demo:latest'